// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getPoly
arma::mat getPoly(arma::mat samples, arma::mat derivatives, Rcpp::List combinations);
RcppExport SEXP _ZVCV_getPoly(SEXP samplesSEXP, SEXP derivativesSEXP, SEXP combinationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type derivatives(derivativesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type combinations(combinationsSEXP);
    rcpp_result_gen = Rcpp::wrap(getPoly(samples, derivatives, combinations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ZVCV_getPoly", (DL_FUNC) &_ZVCV_getPoly, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ZVCV(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
